// Base URL
@baseUrl = http://localhost:3000/api

###
// 1. Get all messages
GET {{baseUrl}}/messages

###
// 2. Create a new message
POST {{baseUrl}}/messages
Content-Type: application/json

{
  "content": "Message sent from REST Client"
}

###
// 3. Get message by ID SUCCESS
GET {{baseUrl}}/messages/4

###
// 4. Edit message (using PATCH)
PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
  "content": "Message updated from REST Client"
}

###
// 5. Delete a single message by ID
DELETE {{baseUrl}}/messages/3

###
// 6. Delete all messages
DELETE {{baseUrl}}/messages
